"""ShortCandidateSelectionTask — Long-Short Phase 2B.

Populates ``ctx.short_candidates`` with the bottom-decile of panel-LTR
scores when ``long_short.enabled = true``. No-op when disabled.

The QP solver (``BuildSourceMapTask``) already reads from
``ctx.short_candidates`` if present (Phase 2A wiring). This task fills
that source with bottom-of-rank names.

Selection logic
---------------
1. Read full-universe panel scores from ``ctx._panel_scores_all`` (stashed
   by ``ApplyScoresTask``).
2. Exclude tickers already held long (``ctx.holdings``) — can't be both
   long and short same security.
3. Exclude ETFs from a static blacklist (avoid shorting index funds).
4. Exclude tickers flagged non-shortable in `data/alpaca_borrow_status.json`
   (Phase 2B-Alpaca-research 2026-05-14).
5. Take the bottom ``short_decile`` fraction (default 0.10 → bottom 10%).
6. Cap at ``max_shorts`` (default 5) by lowest score.
7. Wrap each in a ``CandidateResult`` with the panel score; negative
   score signals "short" intent.

References
----------
* Grinold-Kahn 1999 §5 — IR = IC × √breadth. Adding shorts doubles
  breadth → IR×√2 ≈ 40% improvement (theoretical).
* López de Prado, AFML 2018 §10 — meta-labeling for bet sizing.

Config (in side config, OFF by default):

    "long_short": {
      "enabled": true,
      "short_decile": 0.10,
      "max_shorts": 5,
      "etf_blacklist": ["SPY", "GLD", "QQQ", "IWM", "DIA"],
      "max_short_pct": 0.05,
      "max_gross_exposure": 1.30
    }

`max_short_pct` and `max_gross_exposure` are consumed by
``ComputeQPConstraintsTask`` — already wired in Phase 2A.
"""
from __future__ import annotations

import logging

from kernel.pipeline.context import InferenceContext
from kernel.pipeline.pipeline import Task

log = logging.getLogger("kernel.pipeline.task_short_candidates")


# Default static ETF blacklist (non-individual-equity instruments).
# Override via `long_short.etf_blacklist` in config.
DEFAULT_ETF_BLACKLIST = frozenset({
    "SPY", "GLD", "QQQ", "IWM", "DIA", "TLT", "HYG", "LQD", "VXX",
    "XLF", "XLE", "XLK", "XLV", "XLY", "XLP", "XLI", "XLB", "XLU", "XLRE",
})


def _load_borrow_status(path: str = "data/alpaca_borrow_status.json") -> dict:
    """Load shortable/easy_to_borrow flags fetched from Alpaca live API.

    Fail-open: if missing, returns {} — caller treats all tickers as
    shortable (matches Phase 2A behavior). Real prod risk is bounded
    because Alpaca rejects short orders on non-shortable names; sim is
    the only place a "non-shortable" filter matters for correctness.

    Generated by `scripts/fetch_alpaca_borrow_status.py` (see).
    Fields:
        results[ticker] = {
            "shortable": bool, "easy_to_borrow": bool,
            "marginable": bool, "tradable": bool
        }
    """
    from pathlib import Path  # noqa: PLC0415
    import json as _json  # noqa: PLC0415
    p = Path(path)
    if not p.exists():
        return {}
    try:
        return _json.loads(p.read_text()).get("results", {})
    except Exception:
        return {}


class ShortCandidateSelectionTask(Task):
    """Phase 2B: pick bottom-decile of panel scores as short candidates.

    No-op when ``long_short.enabled`` is false (default).
    """

    name = "ShortCandidateSelectionTask"

    def run(self, ctx: InferenceContext) -> bool | None:
        ls_cfg = (getattr(ctx, "config", None) or {}).get("long_short", {}) or {}
        if not ls_cfg.get("enabled", False):
            ctx.short_candidates = []  # ensure attribute exists
            return None

        # BEAR regime — no shorts (defensive). Phase 2A also skips shorts
        # at the QP constraint layer for BEAR, but we short-circuit here
        # to save the work too.
        if getattr(ctx, "bear_only", False):
            ctx.short_candidates = []
            log.info("ShortCandidateSelectionTask: BEAR mode → no shorts")
            return None

        scores = getattr(ctx, "_panel_scores_all", None)
        if scores is None or len(scores) == 0:
            log.warning(
                "ShortCandidateSelectionTask: ctx._panel_scores_all "
                "missing — was ApplyScoresTask run? Skipping shorts."
            )
            ctx.short_candidates = []
            return None

        # Exclusion sets — only ACTIVELY HELD tickers (overlap with long
        # candidate pool is OK; `BuildSourceMapTask` precedence guarantees
        # the long candidate wins when a ticker is in both sets).
        # Pre-fix this also excluded ctx.candidates (the broad admission
        # pool of 60-70 tickers), leaving the eligible set empty in 2026-05-14
        # smoke. The intent was "don't short tickers we're about to buy long" —
        # but ctx.candidates ⊃ {actual longs}, so excluding the whole pool
        # over-filters. The QP's source-map merging already handles overlap.
        held_tickers = set((ctx.holdings or {}).keys())
        blacklist = frozenset(
            ls_cfg.get("etf_blacklist", DEFAULT_ETF_BLACKLIST)
        )

        # Filter and sort ascending (lowest panel score first)
        eligible = scores.dropna().sort_values(ascending=True)
        eligible = eligible[~eligible.index.isin(held_tickers)]
        eligible = eligible[~eligible.index.isin(blacklist)]

        # Alpaca shortable-status filter (2026-05-14 research):
        # all 103 in current watchlist are shortable + ETB, but this
        # protects against future universe expansion that may include
        # HTB or non-shortable names. Fail-open: if status file missing,
        # treat all as shortable (matches Phase 2A behavior).
        borrow_status = _load_borrow_status(
            ls_cfg.get("borrow_status_path", "data/alpaca_borrow_status.json")
        )
        if borrow_status:
            non_shortable = {
                t for t, info in borrow_status.items()
                if isinstance(info, dict) and info.get("shortable") is False
            }
            if non_shortable:
                pre_n = len(eligible)
                eligible = eligible[~eligible.index.isin(non_shortable)]
                if len(eligible) < pre_n:
                    log.info(
                        "ShortCandidateSelectionTask: filtered %d non-shortable tickers",
                        pre_n - len(eligible),
                    )

        if len(eligible) == 0:
            ctx.short_candidates = []
            log.info("ShortCandidateSelectionTask: 0 eligible after filters")
            return None

        # Take bottom decile, capped at max_shorts
        short_decile = float(ls_cfg.get("short_decile", 0.10))
        max_shorts = int(ls_cfg.get("max_shorts", 5))
        n_bottom = max(1, int(len(eligible) * short_decile))
        n_picked = min(n_bottom, max_shorts)
        picks = eligible.head(n_picked)

        # Wrap in CandidateResult objects.
        # 2026-05-14 fix: NEGATE panel_score so the QP sees a negative μ
        # for short candidates → optimal w is negative → actual short
        # allocation. Pre-fix the bottom-decile panel_score was passed
        # raw, but XGBoost rank:pairwise outputs are typically positive
        # for the whole universe; "bottom decile" = small positive, not
        # negative. With μ > 0 the QP optimum is w > 0 (long). The
        # absolute value preserves magnitude for risk weighting; sign
        # flip is the directional signal.
        from kernel.selection import CandidateResult  # noqa: PLC0415
        ctx.short_candidates = []
        for t, v in picks.items():
            score_sign_flipped = -abs(float(v))   # always non-positive
            ctx.short_candidates.append(CandidateResult(
                ticker=t,
                raw_score=float(v),                # preserve raw for telemetry
                rank_score=float(v),
                rs_score=0.0,
                detail=f"short_candidate raw_panel_score={v:.4f} → mu={score_sign_flipped:.4f}",
                expected_return=score_sign_flipped,  # negative
                panel_score=score_sign_flipped,      # negative — drives QP shorting
            ))
        log.info(
            "ShortCandidateSelectionTask: %d short candidates picked "
            "(bottom %.0f%%, max_shorts=%d) — tickers=%s",
            len(ctx.short_candidates), short_decile * 100, max_shorts,
            [c.ticker for c in ctx.short_candidates],
        )


__all__ = ["ShortCandidateSelectionTask", "DEFAULT_ETF_BLACKLIST"]
