#!/usr/bin/env bash
# Shared shell helpers for resolving RenQuant subrepo source roots.
#
# Default root is the sibling GitHub directory. Production can override with
# RENQUANT_SUBREPO_ROOT, typically generated by scripts/subrepo_assemble.py
# --runtime-root, so scheduled wrappers import isolated lock-pinned clones
# instead of developer worktrees.

renquant_subrepo_root() {
    local repo_dir="${1:?repo_dir required}"
    local default_root="${2:-}"
    if [ -z "$default_root" ]; then
        default_root="$(cd "$repo_dir/.." && pwd)"
    fi
    printf '%s\n' "${RENQUANT_SUBREPO_ROOT:-$default_root}"
}

renquant_subrepo_src() {
    local root="${1:?root required}"
    local repo="${2:?repo required}"
    printf '%s/%s/src\n' "$root" "$repo"
}

renquant_subrepo_pythonpath() {
    local root="${1:?root required}"
    shift
    local out=""
    local repo
    for repo in "$@"; do
        if [ -n "$out" ]; then
            out="$out:"
        fi
        out="$out$(renquant_subrepo_src "$root" "$repo")"
    done
    printf '%s\n' "$out"
}
